apiVersion: v1
kind: Service
metadata:
        name: api-server-service
        namespace: ingress-nginx
spec:
        type: NodePort
        ports:
                - targetPort: 4000
                  port: 80
                  nodePort: 30018
                  protocol: TCP
        selector:
                app: api-server-module
                type: back-end

