apiVersion: v1
kind: Service
metadata:
        name: ui-module-service
        namespace: ingress-nginx
spec:
        type: NodePort
        ports:
                - targetPort: 3000
                  port: 80
                  nodePort: 30008
                  protocol: TCP
        selector:
                app: ui-module
                type: front-end

