apiVersion: v1
kind: Service
metadata:
        name: user-management-service
        namespace: ingress-nginx
spec:
        type: NodePort
        ports:
                - targetPort: 4000
                  port: 80
                  nodePort: 30038
                  protocol: TCP
        selector:
                app: user-management
                type: back-end

