apiVersion: apps/v1
kind: Deployment
metadata:
        name: add-project-deployment
        namespace: ingress-nginx
        labels:
                app: add-project-deployment
                type: deployment
spec:
        template:
                metadata:
                        name: add-project-module
                        labels:
                                app: add-project-module
                                type: back-end
                spec:
                        containers:
                                -  name: add-project-module
                                   image: dhanuman/architects2019:ADDPROJECTS_43d61b_2019
        replicas: 3
        selector:
                matchLabels:
                        app: add-project-module
                        type: back-end



